<template>
  <div>
    <div class="card">
      <div class="card-title">Generate National Report</div>
      <div class="form-grid fg-3">
        <div class="form-group"><label class="form-label">Report Type</label>
          <select class="form-input"><option>Payroll Summary (All Schools)</option><option>Increment Register</option><option>NPS/PRAN Status</option><option>GIS Deductions</option><option>Special Allowances</option><option>Headcount by Region</option></select>
        </div>
        <div class="form-group"><label class="form-label">Region</label>
          <select class="form-input"><option>All Regions</option><option>North</option><option>South</option><option>East</option><option>West</option><option>Central</option></select>
        </div>
        <div class="form-group"><label class="form-label">Month / Year</label>
          <select class="form-input"><option>April 2026</option><option>March 2026</option><option>February 2026</option></select>
        </div>
        <div class="form-group"><label class="form-label">Output Format</label>
          <select class="form-input"><option>Excel</option><option>PDF</option><option>On-screen</option></select>
        </div>
      </div>
      <div style="display:flex;justify-content:flex-end"><button class="btn btn-primary btn-sm">Generate Report</button></div>
    </div>
    <div class="card">
      <div class="card-title">Recently Generated Reports</div>
      <table>
        <thead><tr><th>Report Name</th><th>Generated By</th><th>Date</th><th>Records</th><th>Format</th><th></th></tr></thead>
        <tbody>
          <tr v-for="r in reports" :key="r.name">
            <td style="font-weight:600">{{ r.name }}</td>
            <td>{{ r.by }}</td><td>{{ r.date }}</td><td>{{ r.records }}</td>
            <td><span class="badge b-blue">{{ r.format }}</span></td>
            <td><button class="btn btn-sm btn-icon">⬇</button></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script setup>
const reports = [
  { name:'April 2026 Payroll Summary',    by:'NESTS Admin', date:'05 May 2026', records:'9,266', format:'Excel' },
  { name:'GIS Deductions – Apr 2026',     by:'NESTS Admin', date:'05 May 2026', records:'9,266', format:'Excel' },
  { name:'Increment Register – Jul 2026', by:'NESTS Admin', date:'01 May 2026', records:'218',   format:'PDF'   },
]
</script>
